### ISSUE TITLE
can't filter on form elements

### ISSUE THREAD

**Issue by aquamoth** [sunnywalker/jQuery.FilterTable#50]
I have used filterTable for quite some time and love it.
However, now I have a long table full of textboxes, selects and textareas. 
Those elements does not seem to be part of the filtering rules.

Do you have any tips on how to tweak the component to see inside those elements too?

**Comment by sunnywalker** [comment]
The filtering calls `.text()` from jQuery to filter out tags to prevent the tag name and parameters from showing up in the search (e.g., searching on “put“ would catch all `<input>` tags). You could probably easily modify the `$.expr[':'].filterTableFind` and `$.expr[':'].filterTableFindAny` pseudo selectors to return `$(el).find('input,textarea').val()…` instead of `$(el).text()…` as long as all your table cells only have either an input or textarea. But if you have some `td` with inputs/textareas and some with just text, you'd need a more robust function to figure out how to search both or each. That's a pretty messy solution but the only one I can think of.
